### ISSUE TITLE
Add common labels to client config

### ISSUE THREAD

**Issue by yolocs** [abcxyz/lumberjack#161]
```yaml
version: v1alpha1
# ...
labels:
  foo: bar
```

The labels would be set to the labels for all the logs we send. If there is a conflict, the one presents in the log should win. This feature is helpful to pass down any static data required in the logs.
