### ISSUE TITLE
Fix inconsistency in config loading between Java and Go

### ISSUE THREAD

**Issue by yolocs** [abcxyz/lumberjack#203]
For a sample config

```yaml
backend:
  remote:
    address: "" # empty
```

In Go, it will return an error saying `address` is required for a remote backend config.
In Java, it won't return an error; instead, it will treat that as a remote backend is not needed (enabled).
