### ISSUE TITLE
Go: User should be able to specify a list of `fromRawJWT` in the config instead of just one `fromRawJWT`

### ISSUE THREAD

**Issue by NoamRabbani** [abcxyz/lumberjack#73]
Currently, this config invalid in the Go client, but valid in the Java client:

```
security_context:
    from_raw_jwt:
      - key: foo
         prefix: bar
      - key: foo2
        prefix: bar2
```
