### ISSUE TITLE
Java / Add better handling around missing values in YAML 

### ISSUE THREAD

**Issue by raserva** [abcxyz/lumberjack#78]
Right now a basic config might look like the following:

```
version: v1alpha1
condition:
  regex:
    principal_include:
    principal_exclude:
backend:
  address:
  insecure_enabled: false
  impersonate_account:
security_context:
  from_raw_jwt:

rules:
- selector: "*"
  directive: AUDIT_REQUEST_AND_RESPONSE
```

If the values are empty, this works file, however if you omit the empty blocks, it errors. 

```
version: v1alpha1

security_context:
  from_raw_jwt:

rules:
- selector: "*"
  directive: AUDIT_REQUEST_AND_RESPONSE
```

This should be updated to handle the missing keys more gracefully.
